### ISSUE TITLE
Add a theme linter?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#108]
Not sure if we want to build something w/ [**ajv**](http://npm.im/ajv), or [**joi**](http://npm.im/joi), or your schema validator of choice to make sure we're validating themes so that they don't have any extra/missing properties. Will also make it easier to validate theme data in the future if we add names (#91) or additional properties (#70).

I had a couple lame ideas in https://github.com/mozilla/ThemesRFun/pull/106#issuecomment-369137906.

**Comment by lmorchard** [comment]
This could be a good idea to go along with separating out the themes as individual JSON files from constants.js

**Comment by pdehaan** [comment]
I also found it a little odd that the `defaultColors` constant has the exact same values, as `presetColors[0]`.

https://github.com/mozilla/ThemesRFun/blob/a57c5b5a231e669193662091138ea5bd8c963e27/src/lib/constants.js#L21-L54

https://github.com/mozilla/ThemesRFun/blob/a57c5b5a231e669193662091138ea5bd8c963e27/src/lib/constants.js#L56-L90

Not sure if it'd be better to just do:

```js
export const presetColors = [
  {...defaultColors},
  blah,
};
```

I was trying to use [**glob**](http://npm.im/glob) in ./src/lib/constants.js to grab my extracted preset themes from ./src/lib/presets/\*.json, but it was seemingly failing somewhere since I don't think I'm running in a Node context in ./src/lib/*. Using **glob** otherwise worked great when running my schema linter locally via `$ babel-node schema-lint-joi`. Although explicitly importing each preset manually using something like this worked in ./src/lib/constants.js:

```js
import preset1 from './presets/1.json';
import preset2 from './presets/2.json';
import preset3 from './presets/3.json';
import preset4 from './presets/4.json';
import preset5 from './presets/5.json'; // Hotdog Stand 🌭
```

**Comment by lmorchard** [comment]
> I also found it a little odd that the defaultColors constant has the exact same values, as presetColors[0].

`defaultColors` predates the preset colors feature just slightly, so I guess it was just a good copypasta candidate.

> I was trying to use glob in ./src/lib/constants.js to grab my extracted preset themes from ./src/lib/presets/*.json, but it was seemingly failing somewhere since I don't think I'm running in a Node context in ./src/lib/*. 

What I'm planning to do is use [Webpack's require context feature](https://webpack.js.org/guides/dependency-management/), which lets you require a set of assets from a directory. I do that [over here for background images](https://github.com/mozilla/ThemesRFun/blob/master/src/web/lib/components/ThemeBackgroundPicker/index.js#L10) and it works pretty well to bundle everything up.

**Comment by pdehaan** [comment]
> What I'm planning to do is use Webpack's require context feature,

That's beautiful! 💯

**Comment by Shruti9520** [comment]
Hi, @pdehaan @lmorchard Can I work on this issue? :-)

**Comment by Shruti9520** [comment]
Hi, @pdehaan  @lmorchard When I open `/src/lib/constants.js` file, I can't see `defaultColors` and `presetColors ` constants. You can see that by clicking this link- https://github.com/mozilla/Themer/blob/master/src/lib/constants.js.

But @pdehaan addresses this link- https://github.com/mozilla/ThemesRFun/blob/a57c5b5a231e669193662091138ea5bd8c963e27/src/lib/constants.js#L21-L54  where I can see those constants clearly.

How to generate these different URLs? I am sorry if I sound stupid but I am curious to know. :-) 

Thanks!

**Comment by lmorchard** [comment]
> Hi, @pdehaan @lmorchard When I open /src/lib/constants.js file, I can't see defaultColors and presetColors constants.

@Shruti9520 What you're seeing here is that [things have changed](https://github.com/mozilla/Themer/commit/dda7ff752e60be6322dd3f8d1fc34d69358e91cf) since this issue was first created:

1. We removed the defaultColors and presetColors constants
1. We created [lib/themes.js](https://github.com/mozilla/Themer/blob/master/src/lib/themes.js) with defaultTheme and presetThemes - these now read the data for themes from [individual JSON files in src/preset-themes](https://github.com/mozilla/Themer/tree/master/src/preset-themes)

So, the task for this issue now is to build a validation step that checks those JSON files under src/preset-themes

**Comment by pdehaan** [comment]
> But @pdehaan addresses this link- https://github.com/mozilla/ThemesRFun/blob/a57c5b5a231e669193662091138ea5bd8c963e27/src/lib/constants.js#L21-L54 where I can see those constants clearly.
> 
> How to generate these different URLs? I am sorry if I sound stupid but I am curious to know.

@Shruti9520, sorry, the links I generated earlier were pinned to a specific Git commit, which (as you can see) can get stale as the code changes. You can see in the URL and the "Tree" dropdown near the top that my code was pinned to the a57c5b5a231e669193662091138ea5bd8c963e27 commit, so you'll want to switch to the master branch to see the latest code.

![themer_constants_js_at_a57c5b5a231e669193662091138ea5bd8c963e27_ _mozilla_themer](https://user-images.githubusercontent.com/557895/37303383-89acdfbc-25eb-11e8-9ff5-fc265b1bbae7.png)

As for your second question, if you _want_ to generate a code snippet/URL that is pinned to a specific permanent line of code, you can (a) click on a line number, (b) click the `...` icon that should appear to the left of the line number, then (c) select "Copy permalink" from the little popup menu.
Something like this:

![copy-permalink](https://user-images.githubusercontent.com/557895/37303506-dfbf7d74-25eb-11e8-9011-14dff1f5687a.png)

But be careful, as the generated URL will be pinned to that commit, and won't change/update along with the code (which can be good and bad).

**Comment by Shruti9520** [comment]
@pdehaan Thanks for the explanation. :-)

**Comment by Shruti9520** [comment]
@lmorchard Working on this issue. :-)

**Comment by pdehaan** [comment]
Actually, another fun tip; I believe that Themer/src/preset-themes/005.json has an invalid value, so you could probably use that file to see if the linter catches it.

**Comment by Shruti9520** [comment]
Hi @pdehaan @lmorchard I wrote a JSON schema validator. I tested it online for Themer's JSON files and it is working fine. Can I post it here? Before making PR, I just want to be sure whether I am going in right direction or not. :-)

Thanks!

**Comment by pdehaan** [comment]
@Shruti9520, 

If it's short, you could post it here. 
If it's big, you could post it to a Gist.
If you want lots of feedback, you could just submit the PR and we could comment inline.

**Comment by Shruti9520** [comment]
@pdehaan @lmorchard Here is the link to my gist file- https://gist.github.com/Shruti9520/609317dd5c78c7b0402c821712ba7daf

I've tested manually by giving the whole json. The better way would be like this I guess-
`test("link to the json file")`. But I am not sure for this. May be I can use  Webpack's require context feature.

Thanks!

**Comment by lmorchard** [comment]
For this, you could just use [node's fs module](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_readfilesync_path_options) and read the JSON files directly, using JSON.parse() to parse them before testing them. We could run it alongside [other npm script commands we use for linting & validating](https://github.com/mozilla/Themer/blob/master/package.json#L31).

**Comment by pdehaan** [comment]
@Shruti9520 Great job, this looks fantastic!

Did it end up catching the bug in https://github.com/mozilla/Themer/blob/master/src/preset-themes/005.json?

I actually think this is good enough that you could submit the PR for it, and we can make a few comments directly in the code before merging.

Warning: I'll probably make a comment about the indenting being a bit tricky to read. Maybe try running the code through [**prettier**](http://npm.im/prettier) using something like this:

```sh
$ npx prettier JsonSchema.js --write
```

There are a few other small things, but probably easier to save them until we can comment on specific lines to give some better context.

**Comment by Shruti9520** [comment]
@lmorchard Thanks! I will do that.
@pdehaan Yes. On running `/src/preset-themes/005.json`, I am getting this error--> `Invalid: data.title should be string, data.colors should be object`. This was the only bug, right?
Also, I'll make sure to use ` prettier ` before raising a PR. Thanks!

**Comment by pdehaan** [comment]
@Shruti9520 Yeah, the bug is that we nested the `title` property in the wrong place:

https://github.com/mozilla/Themer/blob/bf60c3d9250496b289c03b5d77182c866bf56435/src/preset-themes/005.json#L1-L9

It should be outside of the `colors` object.
I think the other error is wrong, but only because you're linting an incorrect object in your Gist and not the actual ./src/preset-themes/005.json file (which has a slightly different structure):

```js
{
  "colors": "005",
  "title": {
    "toolbar": {
      "h": 4,
      "s": 0,
      "l": 10,
      "a": 10.00
    },
    // ...
  }
}
```
