### ISSUE TITLE
[Enhancement] The "Firefox Theme Generator" tab should be focused if already open when the "ThemesRFun" toolbar button is pressed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#119]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "ThemesRFun" add-on (0.0.24 custom build from 07.03.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Press the "ThemesRFun" toolbar button and open/focus another tab.
3. Press the "ThemesRFun" toolbar button again and observe the behavior.

**[Expected result]:**
- The "Firefox Theme Generator" tab is focused.

**[Actual result]:**
- A new "Firefox Theme Generator" tab is opened.

**[Notes]**:
- If an "about:addons"/"about:preferences" tab is already opened, clicking the "Add-ons"/"Options" button will focus the existing tab. Considering this we think that we should do the same with the "Firefox Theme Generator" tab.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37087867-35f86020-2204-11e8-86d3-b44c092b91a3.gif)

**Comment by Shruti9520** [comment]
@Softvision-MariusComan @lmorchard What is the difference between `Themer` repo and `ThemeRFun`?
How are they related? Also, I can't find any `ThemeRFun` as described in the issue- https://github.com/mozilla/Themer/issues/41

Thanks!

**Comment by pdehaan** [comment]
@Shruti9520 “ThemesRFun” was the beta name, and “Themer” is the final name. We just renamed the repo and all code references, etc.

**Comment by Madhumathi97** [comment]
@Softvision-MariusComan Can I take this up as my first contribution for the project "Improve sharing & contribution features on Firefox Themer for Test Pilot"

**Comment by lmorchard** [comment]
@Madhumathi97 It looks like @cedricium has this one covered in PR #160
