### ISSUE TITLE
Reconsider the use of headerURL in the web app/preset themes

### ISSUE THREAD

**Issue by johngruen** [mozilla/Themer#126]
So, in the app, we're using `headerURL` to refer to images, but in the add-on we're actually displaying images through the `additional_backgrounds` array. In order to better align the vocabulary we're using in our preset themes, the site, and the add-on, we should change preset themes so that the images section has no headerURL, but does optionally have an additional_backgrounds array. Also, we go through the app components and scrub any references to the headerURL in favor of `additional_backgrounds`

**Comment by lmorchard** [comment]
At one point, I tried taking out headerURL. That meant backgrounds didn't work at all.

[So I replaced headerURL with a 1x1 image](https://github.com/mozilla/Themer/pull/54) - `additional_backgrounds` were ignored until I did that. Maybe this is a bug that's fixed upstream since then?

**Comment by johngruen** [comment]
Yeah i think so...that PR i just made makes the headerURL optional in the add-on based on the FF version. We should clean up the app to reflect that we're not actually using it.
