### ISSUE TITLE
The "Firefox Theme Generator" page buttons wrongly overlap when the browser is resized

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#131]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Resize the browser to half window.
4. Observe the page buttons.

**[Expected result]:**
- All buttons are fully visible.

**[Actual result]:**
- The page "Theme Texture" button overlap the "Background Tab Text Color" one.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37158119-3f51d12a-22f3-11e8-82b7-69a87e2ffb6d.gif)

**Comment by johngruen** [comment]
Closing in favor of #41
