### ISSUE TITLE
The "Themer" toolbar button icon is too bright when the browser's dark theme is activated

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#132]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons>Themes and enable the "Dark" theme.
3. Observe the "Themer" toolbar button icon.

**[Expected result]:**
- The icon has the same color as the other toolbar icons.

**[Actual result]:**
- The icon is too bright.

**[Notes]:**
- The issue is not reproducible with the "Show Sidebars" or with the "View history, saved bookmarks, and more" button's icons.
- The issue is not reproducible if you set a different color using "Themer".
- Also it looks like the "Themer" button's icon does not respect the opacity propriety.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37158299-ba89aab6-22f3-11e8-95e8-58d5cbbf4d75.gif)

**Comment by lmorchard** [comment]
I think #130 fixed this?

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest master using Windows 10 x64, Ubuntu 16.04 x32 and Mac 10.13.3.
