### ISSUE TITLE
Add and update all the tooltips

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#133]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Hover all the page elements and observe the displayed tooltips.
4. Click the "Toolbar Color" button.
5. Hover all the elements and observe the color picker's displayed tooltips.

**[Expected result]:**
- Step 3 & 5: All the buttons and the fields have tooltips.

**[Actual result]:**
- Step 3: 
1) No tooltips: 
         - All the buttons that trigger the color pickers.
         - The "Copy" button, the "Save" button.
         - The "Twitter" and "GitHub" buttons from the footer.
						  
2) Lowercase tooltips: 
        - The "Undo" and the "Redo" buttons. 
        - The saved theme's "Delete" button.
		  
3) Wrong tooltips: 
        - The "survey link" tooltip is displayed for the The "Feedback" button.
        - The "notification-16" tooltip is displayed for the The "Feedback" icon.
		  
- Step 5: There are no tooltips displayed at all.

**[Notes]:**
- The issue is reproducible for all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37158718-b78731a2-22f4-11e8-9c3d-54f14c398c50.gif)

**Comment by csd713** [comment]
Hello @Softvision-MariusComan I would like to take this up. I'm able to reproduce the issue locally.
I was wondering if there is any specific development document that I could use for PR process.

**Comment by pdehaan** [comment]
@csd713,

I don't think we have any specific PR documentation in this repo specfically, but this is probably a good starting point for most of the Test Pilot experiments: https://github.com/mozilla/testpilot/blob/master/CONTRIBUTING.md

Let us know if you have any specific questions and we'd be happy to help.

**Comment by csd713** [comment]
Hi @pdehaan,

What is the expected result for,

1. the buttons that trigger the color pickers - (should the name of the button be used as tooltip ?)
2. each button/fields in color picker pallet ?

**Comment by lmorchard** [comment]
For lack of a better idea, I think we could just add a title attribute for each of these that matches the text title already there for each item. Seems redundant, but I don't think we had any plan to add tooltips for these
