### ISSUE TITLE
The "Themer" add-on wrongly overrides the existing Firefox Theme

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#134]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile. 

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Install the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) from the "about:debugging" page.
3. Click the "Themer" toolbar button.
2. Navigate to about:addons>Themes and observe the enabled theme.

**[Expected result]:**
- All themes are disabled.

**[Actual result]:**
- The Firefox "Default" theme is enabled.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37159092-9ac85414-22f5-11e8-8f3f-6ab894bce987.gif)

**Comment by johngruen** [comment]
This is just how WebExtensions themes work in the browser. I think we should close this.

**Comment by lmorchard** [comment]
Yeah, there is a conflict between how various kinds of themes work right now, more an upstream issue than anything we can affect on this project
