### ISSUE TITLE
The actual theme is wrongly changed when the "Themer" button is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#135]
**[Notes]:**
- Depending on the decision that will be taken in #134, we need to consider that most users will not expect their current theme to be changed to a random one when clicking the "Themer" button. Especially since the only ways to revert the changes are too either disable and re-enable the theme or uninstalling the add-on.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.
- Have a Firefox different theme then default activated (e.g. Dark theme).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button and observe the behavior.

**[Expected result]:**
- The actual Firefox theme remains the same.
or
- An onboarding tour start which explains what the add-on does and lets the user decide to change the theme or not.

**[Actual result]:**
- The current theme is changed to the "Themer" default one.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37159249-08bb9224-22f6-11e8-958d-e81be2ecf222.gif)

**Comment by lmorchard** [comment]
Basically the same issue as #134 - a webextension based theme will override one of the default themes when updated.
