### ISSUE TITLE
The cursor wrongly changes into "horizontal move" when a color picker letter (R,G,B,A) is hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#138]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button and press the "Toolbar Color" button.
3. Place the mouse cursor on a letter and observe the behavior.
Extra
4. Click and drag the mouse to the left or to the right.

**[Expected result]:**
- Step 3 & 4: Nothing happens.

**[Actual result]:**
- Step 3: The mouse cursor changes into a horizontal double arrow.
Extra
- Step 4 - The color slider is moved.

**[Notes]:**
- If the R, G, or B letters are clicked and dragged the color slider is moved.
- If the A letter is clicked and dragged the opacity slider is moved.
- This issue is reproducible with all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37162678-8740d890-22fe-11e8-98a5-273226d60dd8.gif)

**Comment by lmorchard** [comment]
This is an expected feature for the component: The arrow pointer indicates that dragging will change the color value.

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard But why do we have the drag functionality on that area when there is a slider that does the exact same thing? I agree that it's an edge case, but still, I don't think it's right.
