### ISSUE TITLE
Add CONTRIBUTING.md with some steps on how to get started on good-first-bugs and the PR process

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#143]
Per https://github.com/mozilla/Themer/issues/133#issuecomment-371684872

**Comment by Shruti9520** [comment]
Hi @pdehaan Can I take this issue? :-)

**Comment by lmorchard** [comment]
Help on this issue would be much appreciated! Even if you just try getting started with the project and taking notes as to where you run into trouble or have questions. Those of us who have already been working on the project may be prone to forgetting all the little things that a beginner needs to know, so a fresh perspective would be very helpful!

**Comment by Shruti9520** [comment]
@lmorchard Thanks :-)

**Comment by Madhumathi97** [comment]
@Shruti9520 Did you already contribute to this bug?Or can I take it?

**Comment by Shruti9520** [comment]
Hi, @Madhumathi97 I submitted a PR- https://github.com/mozilla/Themer/pull/153 for this. :-)

**Comment by Madhumathi97** [comment]
@Shruti9520 Just realised that.Thanks!

**Comment by Shruti9520** [comment]
@Madhumathi97 Here is the link for good first issues- https://github.com/mozilla/Themer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22.
Hope it helps. :-)

Thanks!

**Comment by Madhumathi97** [comment]
@Shruti9520 Great!Thank you:)

**Comment by lmorchard** [comment]
bf513ad7997b3f74ce27df8cd98440b12c626bbe
