### ISSUE TITLE
Add a QA test plan

### ISSUE THREAD

**Issue by wresuolc** [mozilla/Themer#164]
Maybe this already exists?  @Softvision-MariusComan

**Comment by Softvision-MariusComan** [comment]
Yes, we already have a test plan for Themer. You can find it [here](https://docs.google.com/document/d/1jYxZkD6D1P_MBPu0q-5AwFm7tdY9cWY2q6huiWdTDEE/edit#).
However the test plan is not in its final form because we plan to split "Themer functionality" test objective into separate cases.

**Comment by wresuolc** [comment]
Great, thanks.  Existing is what we want to confirm.  No need to have a bug open for needing updates.  Thanks!
