### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/Themer#171]
The page is not responsive. The icons are overlapping each other when we are changing the screensize.

Should I work upon this issue ?

![screenshot from 2018-03-14 20-16-22](https://user-images.githubusercontent.com/34654829/37409790-2d020694-27c5-11e8-8777-95685e66d6ff.png)

**Comment by Softvision-MariusComan** [comment]
@gargshruti30 Thank you for reporting this. However this behavior is already tracked in issue #41. 
Considering this I am closing this issue as a duplicate.
