### ISSUE TITLE
Replace preloader UI w/ logo?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#173]
I'm seeing this preloader flash in as https://mozilla.github.io/Themer/ loads. Not sure if we wanted to use our fancy new logo or if this is final UI. 🤷‍♀️ 

![firefox_themer](https://user-images.githubusercontent.com/557895/37416148-4a2228c2-276a-11e8-9a97-2434786739d7.png)

**Comment by johngruen** [comment]
Yeah, this is a placeholder...

**Comment by pdehaan** [comment]
@johngruen Can we say you resolved this with your majestic #196 PR, and this can be closed?

**Comment by johngruen** [comment]
yep
