### ISSUE TITLE
The "Color Picker" panel is not dismissed when its button is clicked or the "Esc" key is pressed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/Themer#176]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.31 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Click the "Toolbar Icons and Text" bubbled text.
4. Click the bubble text and observe the behavior.

**[Expected result]:**
- The "Color Picker" panel is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue: 
![color picker dimiss](https://user-images.githubusercontent.com/19226534/37466679-104b977a-2867-11e8-95ba-d81739d1555f.gif)

**Comment by lmorchard** [comment]
I think this is more of an enhancement than a bug: Clicking the button selects the picker. Clicking it again just selects it again, which doesn't change anything. And we don't really have much in the way of keyboard control in the app yet, so Esc isn't expected to do anything.

**Comment by shr7** [comment]
Hi @lmorchard, @SoftVision-CosminMuntean!
Can I take this up?

**Comment by shr7** [comment]
@lmorchard Thank you! PR raised :)
