### ISSUE TITLE
Add CHANGELOG?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#179]
Not sure if we need one, or if it's useful for anybody else (personally I find them useful to know what's changed between versions to know where we should focus testing).

I know TestPilot includes a field for CHANGELOG, but we could always just point that to the GitHub releases page (a  la Notes and other experiments):

![changelog](https://user-images.githubusercontent.com/557895/37489896-55e3695e-2856-11e8-9e7c-355fa5244d7b.png)

**Comment by meandavejustice** [comment]
I've been using https://github.com/nodejs/changelog-maker for Min Vid and it's worked well for me.

[min vid changelog](https://github.com/meandavejustice/min-vid/blob/master/CHANGELOG.md)

**Comment by lmorchard** [comment]
I've usually found changelogs to be redundant, especially when working on a project that deploys often and doesn't necessarily release explicit versions. Seems easier to get a link to commit ranges on github. If we can automate it, it probably wouldn't be a bad addition

**Comment by johngruen** [comment]
I think we can just use the commit history in lieu of a real changelog if its too much overhead
