### ISSUE TITLE
Allow multiple sites to be defined in SITE_URL

### ISSUE THREAD

**Issue by jbuck** [mozilla/Themer#185]
Right now we currently have SITE_URL=https://themer.stage.mozaws.net/ but we'll need to add https://themer.firefox.com to the list for production. The [web extension build process](https://github.com/mozilla/Themer/blob/e727ee21c9179b88fb954c21d3d3c30958c3ad65/webpack.extension.js#L54-L57) only allows a single URL.

I think the best way to do this might be doing something like `manifest.content_scripts[0].matches = process.env.SITE_URL.split()` but that's just me spit-balling.

**Comment by lmorchard** [comment]
The SITE_URL isn't a list, it should be set for the specific deployment. It's included in the build of the add-on to lock it to the exact site it's intended to be used with. I think that's a security requirement. It's also used in the toolbar button to set the site that opens in a tab.

**Comment by jbuck** [comment]
Hmm, okay, is a way we can distinguish between stage and production builds of the Themer add-on? What else would need to change to have two otherwise identical add-ons run side-by-side?

**Comment by lmorchard** [comment]
Might be worth tweaking the add-on ID and title based on an env var? Could be weird or maybe could be beneficial to have different builds of the add-on installed pointed at different site builds
