### ISSUE TITLE
Wrong tooltip is displayed when the Hex, R, G and B text fileds from the "Color Picker" panel are hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#189]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.32 custom build from 2018-03-21) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Toolbar Icons and Text" bubble and hover over each Hex, R, G and B text fields.
3. Observe the displayed tooltip.

**[Expected result]:**
- For each text field a related tooltip is displayed.

**[Actual result]:**
- The "Toolbar Icons and Text" tooltip is displayed for each text field.

**[Notes]:**
- The issue is reproducible with all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37721177-8440bd30-2d31-11e8-843e-7718100d6d5c.gif)

**Comment by lmorchard** [comment]
There's a `title` attribute on the `<li>` in editor elements for ThemeColorsEditor. We could probably solve this just by applying that title to the "color__swatch" and "color__label" child element so that "color__picker" doesn't get the title

**Comment by Shruti9520** [comment]
@lmorchard Can I take this?

**Comment by lmorchard** [comment]
Take it away!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Themer" add-on (0.0.33 custom built on 29.03.2018) installed, on the latest Firefox release and Nightly. Now the tooltips are no longer displayed. Verified on Windows 10 x64, Arch Linux and Mac 10.12.
