### ISSUE TITLE
The "Color Picker" panel is wrongly dismissed if you click inside of any text field

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#190]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.32 custom build from 2018-03-21) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Toolbar Icons and Text" bubble and click inside of any text field. 
3. Observe the behavior.

**[Expected result]:**
- The text caret is displayed in the area where the click action was taken.

**[Actual result]:**
- The "Color Picker" panel is wrongly dismissed.

**[Notes]:**
- The issue is reproducible for all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37721382-f88c44ca-2d31-11e8-9ab0-1777120db54c.gif)

**Comment by shr7** [comment]
Looks like my patch for https://github.com/mozilla/Themer/issues/176 is the culprit behind this issue. :P

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Themer" add-on (0.0.33 custom build from 26.03.2018) installed, on the latest Firefox release and Nightly.
