### ISSUE TITLE
The "Hand" pointer is wrongly displayed when hovering the "Color Picker" backgound area

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#191]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.32 custom build from 2018-03-21) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Toolbar Icons and Text" bubble text. 
3. Hover the "Color Picker" background. 
4. Observe the mouse pointer.

**[Expected result]:**
- The "arrow" pointer is displayed.

**[Actual result]:**
- The "hand" pointer is displayed.

**[Notes]:**
- The issue is reproducible for all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37721451-3425b598-2d32-11e8-97db-bdfcb6a93657.gif)

**Comment by lmorchard** [comment]
Looks like we've got [a `cursor: pointer` applied to the whole picker element in _picker.scss](https://github.com/mozilla/Themer/blob/master/src/web/lib/_picker.scss#L10) - probably better to move that to the specific [swatch](https://github.com/mozilla/Themer/blob/master/src/web/lib/_picker.scss#L104) and [text](https://github.com/mozilla/Themer/blob/master/src/web/lib/_picker.scss#L111) children

**Comment by Shruti9520** [comment]
@lmorchard Can I work on this? :-)

**Comment by lmorchard** [comment]
Go for it!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Themer" add-on (0.0.33 custom built on 29.03.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Arch Linux and Mac 10.12.
