### ISSUE TITLE
The mouse cursor is not changed to a hand pointer when the "Copy" button is hovered

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/Themer#212]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.33 custom build) 
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Hover "Copy" button from  "Share your theme" section.
4. Observe the mouse cursor.

**[Expected result]:**
Mouse cursor changes into a hand pointer.

**[Actual result]:**
Mouse cursor remains the same.

**[Notes]:**
If the "Save" button is hovered, the mouse cursor is changed from an arrow to a hand.
	-attached a screen recording of the issue:
![hover over copy button](https://user-images.githubusercontent.com/37875464/38140597-28732502-343d-11e8-9c66-7be68a8485b6.gif)

**Comment by Shruti9520** [comment]
@Softvision-AndreeaCupsa @lmorchard The possible solution is to include `cursor: pointer` in   https://github.com/mozilla/Themer/blob/215f34a49cfd2b805befbff49badfe1c443fa46b/src/web/lib/components/ThemeUrl/index.scss#L26 file. Can I submit a PR for this?

**Comment by lmorchard** [comment]
Sure, go for it!

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "Themer" add-on (0.0.33 custom built on 02.04.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Arch Linux and Mac 10.13.
