### ISSUE TITLE
Finalize experiment name

### ISSUE THREAD

**Issue by johngruen** [mozilla/Themer#23]

**Comment by lmorchard** [comment]
Trying to think of places this will touch in code, so we don't miss them. Add-on ID, description, site content, etc. Not sure if we want to bother renaming the repo itself on github?

**Comment by johngruen** [comment]
WRT repo, we probably don't need to bother

**Comment by johngruen** [comment]
For the name, Michelle is doing a legal/l10n review for a few different options, should let us know this week.

**Comment by lmorchard** [comment]
Looks like the name needs to change again
