### ISSUE TITLE
Add doco for app state flows?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/Themer#64]
I added this as a comment in `src/web/index.js` in #59. Would be good to find a better place for it. 
```
/**
 * Some notes on the startup flow, here:
 *
 * If there's no ?theme param, just ask for a current theme from the add-on. If
 * the add-on is not installed, this does nothing.
 *
 * If there is a ?theme param, that's considered a theme shared with the user.
 * The shared theme is stored as "pending" and also loaded up into the editor.
 * The add-on is then also asked for a current theme.
 *
 * If the add-on never responds with a current theme, the shared theme just
 * appears in the editor.
 *
 * If the add-on is installed and responds with a current theme, then that
 * current theme is loaded into the editor. 
 *
 * If the shared theme is not identical to the current theme, the "pending"
 * shared theme is pressented in an approval dialog with a preview (i.e.
 * SharedThemeDialog). From there, the user can apply the shared theme to
 * override the current theme or skip it and discard.
 *
 * For more details on this flow, check out src/lib/store.js - pay particular
 * attention to the logic involved in the shouldOfferPendingTheme selector.
 */
```

**Comment by Shruti9520** [comment]
Hi @lmorchard @johngruen 
My name is Shruti Singh. I am a fourth-year undergraduate student from India. I am doing engineering in Computer Science. I have been involved in web development for more than two years. I’ve worked with technologies like JavaScript ( AngularJS), typescript ( Angular 4), Java ( Servlets) and C++.
I would like to work on Mozilla's project "Improve sharing & contribution features on Firefox Themer for Test Pilot" as an Outreachy intern. 
I would like to start with some good first bugs. :-)

Thanks!!

**Comment by lmorchard** [comment]
Hi there! Similar to issue #143 - ideally, we would like a full write-up on how data flows in this application(placed under the docs/ folder. But, it would also be very handy to have any notes or observations on what would be helpful in understanding how the application moves between states

**Comment by shr7** [comment]
Hi @lmorchard 
I'd like to take this up as my first bug for this project if nobody else is working on it.

**Comment by pdehaan** [comment]
@lmorchard Was this fixed by #167, or should we leave it open?

**Comment by lmorchard** [comment]
Seems fine to close

**Comment by pdehaan** [comment]
@arunikayadav42: Welcome!

The best place to start would probably be reviewing the [CONTRIBUTING.md](https://github.com/mozilla/FirefoxColor/blob/master/CONTRIBUTING.md) document, and then looking through the list of open [good first issue](https://github.com/mozilla/FirefoxColor/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)s that you are interested in.
