### ISSUE TITLE
Add twitter/opengraph headers?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#79]
Not sure if these came up in the a11y linting bug results from **sonarwhal** or **lighthouse** tools in https://github.com/mozilla/ThemesRFun/issues/47#issuecomment-368087825 (or anywhere else), but...

Do we want to add [Twitter](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup) and [OpenGraph](http://ogp.me/) meta tags for improved sharing greatness?

```html
<head>
  <meta charset="utf-8">
  <title>Firefox Theme Generator</title>
  <link rel="icon" type="image/svg+xml" href="images/icon.svg">
  <link href="index.css" rel="stylesheet">
  <script type="text/javascript" charset="utf-8" async="" src="https://mozilla.github.io/ThemesRFun/vendor/json-url-msgpack.js"></script>
  <script type="text/javascript" charset="utf-8" async="" src="https://mozilla.github.io/ThemesRFun/vendor/json-url-lzma.js"></script>
  <script type="text/javascript" charset="utf-8" async="" src="https://mozilla.github.io/ThemesRFun/vendor/json-url-safe64.js"></script>
</head>
```

**Comment by Shruti9520** [comment]
@pdehaan @lmorchard Can I work on this? :-)
